from __future__ import annotations

from PySide6.QtCore import QSettings, QSize, QUrl, Qt
from PySide6.QtGui import QAction, QDesktopServices, QIcon, QKeySequence
from PySide6.QtWidgets import (
    QHBoxLayout, QLabel, QLineEdit, QMainWindow, QPushButton, QSplitter,
    QStatusBar, QTabWidget, QTextEdit, QToolBar, QToolButton, QTreeWidget,
    QVBoxLayout, QWidget, QMenu, QPlainTextEdit,
)

from ..config import ICON_PATH, MARKDOWN_DIR
from ..editor import MarkdownEditor
from ..preview import PreviewBrowser
from ..project_list import ProjectListWidget

class UiMixin:

    def build_ui(self):
        toolbar = QToolBar("工具栏")
        toolbar.setMovable(False)
        self.addToolBar(toolbar)
        actions = [
            ("新建", self.new_file, "Ctrl+N"),
            ("保存", self.save_file, "Ctrl+S"),
            ("查找替换", self.show_find_replace, "Ctrl+F"),
            ("导入", self.import_file, "Ctrl+G"),
            ("项目属性", self.edit_project, "Ctrl+L"),
            ("刷新", self.refresh_files, "Ctrl+E"),
        ]
        for label, handler, shortcut in actions:
            action = QAction(label, self)
            action.setShortcut(QKeySequence(shortcut))
            action.setToolTip(f"{label}  ·  {shortcut}")
            action.setStatusTip(f"{label}（{shortcut}）")
            action.triggered.connect(handler)
            toolbar.addAction(action)
        toolbar.addSeparator()
        theme_action = QAction("切换主题", self)
        theme_action.setShortcut(QKeySequence("Ctrl+T"))
        theme_action.setToolTip("切换主题  ·  Ctrl+T")
        theme_action.triggered.connect(self.toggle_theme)
        toolbar.addAction(theme_action)
        self.right_toggle_action = QAction("收起右栏", self)
        self.right_toggle_action.setShortcut(QKeySequence("Ctrl+R"))
        self.right_toggle_action.setToolTip("收起右栏 / 展开右栏  ·  Ctrl+R")
        self.right_toggle_action.triggered.connect(self.toggle_right_panel)
        toolbar.addAction(self.right_toggle_action)
        open_action = QAction("打开数据目录", self)
        open_action.setShortcut(QKeySequence("Ctrl+O"))
        open_action.setToolTip("打开数据目录  ·  Ctrl+O")
        open_action.triggered.connect(lambda: QDesktopServices.openUrl(QUrl.fromLocalFile(str(MARKDOWN_DIR))))
        toolbar.addAction(open_action)

        root = QWidget()
        self.setCentralWidget(root)
        layout = QHBoxLayout(root)
        layout.setContentsMargins(10, 10, 10, 10)
        layout.setSpacing(10)

        left = QWidget()
        self.left_panel = left
        left.setObjectName("panel")
        left_layout = QVBoxLayout(left)
        heading = QHBoxLayout()
        heading.setContentsMargins(6, 4, 6, 4)
        title = QLabel("项目库")
        title.setObjectName("title")
        heading.addWidget(title)
        left_collapse = QToolButton()
        left_collapse.setObjectName("panelCollapseButton")
        left_collapse.setText("‹")
        left_collapse.setToolTip("收起左侧项目库")
        left_collapse.clicked.connect(self.toggle_left_panel)
        heading.addWidget(left_collapse)
        self.count_label = QLabel()
        self.count_label.setObjectName("countBadge")
        heading.addWidget(self.count_label, 0, Qt.AlignRight)
        left_layout.addLayout(heading)
        self.search = QLineEdit()
        self.search.setPlaceholderText("搜索项目名称或内容……")
        self.search.textChanged.connect(self.filter_files)
        left_layout.addWidget(self.search)
        self.filter_button = QToolButton()
        self.filter_button.setObjectName("filterButton")
        self.filter_button.setPopupMode(QToolButton.InstantPopup)
        self.filter_menu = QMenu(self)
        self.filter_menu.triggered.connect(self.set_project_filter)
        self.filter_button.setMenu(self.filter_menu)
        left_layout.addWidget(self.filter_button)
        self.file_list = ProjectListWidget()
        self.file_list.currentItemChanged.connect(self.select_file)
        self.file_list.order_changed.connect(self.persist_project_order)
        self.file_list.delete_requested.connect(self.delete_file)
        self.file_list.setContextMenuPolicy(Qt.CustomContextMenu)
        self.file_list.customContextMenuRequested.connect(self.show_project_context_menu)
        left_layout.addWidget(self.file_list, 1)
        buttons = QHBoxLayout()
        for label, handler in (("＋ 新建", self.new_file), ("项目属性", self.edit_project)):
            button = QPushButton(label)
            button.clicked.connect(handler)
            buttons.addWidget(button)
        self.pin_button = QPushButton("置顶")
        self.pin_button.clicked.connect(self.toggle_project_pin)
        buttons.addWidget(self.pin_button)
        delete_button = QPushButton("删除")
        delete_button.clicked.connect(self.delete_file)
        buttons.addWidget(delete_button)
        left_layout.addLayout(buttons)

        center = QWidget()
        center_layout = QVBoxLayout(center)
        center_layout.setContentsMargins(0, 0, 0, 0)
        self.file_title = QLabel("请选择左侧项目")
        self.file_title.setObjectName("fileTitle")
        file_header = QHBoxLayout()
        self.file_header = file_header
        file_header.addWidget(self.file_title)
        file_header.addStretch()
        self.expand_left_button = QToolButton(root)
        self.expand_left_button.setObjectName("panelExpandButton")
        self.expand_left_button.setText("›")
        self.expand_left_button.setToolTip("展开左侧项目库")
        self.expand_left_button.clicked.connect(self.toggle_left_panel)
        self.expand_left_button.setVisible(False)
        self.expand_right_button = QToolButton()
        self.expand_right_button.setObjectName("panelExpandButton")
        self.expand_right_button.setText("›")
        self.expand_right_button.setToolTip("展开右侧辅助面板")
        self.expand_right_button.clicked.connect(self.toggle_right_panel)
        self.expand_right_button.setVisible(False)
        file_header.addWidget(self.expand_right_button)
        center_layout.addLayout(file_header)
        self.editor = MarkdownEditor()
        self.editor.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.editor_base_font_size = self.editor.font().pointSizeF() if self.editor.font().pointSizeF() > 0 else 10.0
        self.editor_zoom = int(self.settings.value("editor_zoom", 100))
        self.add_markdown_toolbar(center_layout)
        self.editor.textChanged.connect(self.content_changed)
        self.editor.cursorPositionChanged.connect(self.update_status)
        self.preview = PreviewBrowser()
        self.preview.setLineWrapMode(QTextEdit.NoWrap)
        self.preview_base_font_size = 10.0
        self.preview_zoom = int(self.settings.value("preview_zoom", 100))
        self.preview.anchorClicked.connect(lambda url: QDesktopServices.openUrl(url))
        self.preview.image_double_clicked.connect(self.open_preview_image)
        for widget in (self.editor, self.editor.viewport(), self.preview, self.preview.viewport(), self.editor.verticalScrollBar(), self.editor.horizontalScrollBar(), self.preview.verticalScrollBar(), self.preview.horizontalScrollBar()):
            widget.installEventFilter(self)
        self.apply_zoom("editor", self.editor_zoom, update=False)
        self.apply_zoom("preview", self.preview_zoom, update=False)
        self.center_splitter = QSplitter(Qt.Horizontal)
        self.center_splitter.addWidget(self.editor)
        self.center_splitter.addWidget(self.preview)
        self.center_splitter.setChildrenCollapsible(False)
        self.center_splitter.setSizes([500, 500])
        self.last_split_sizes = [500, 500]
        self.current_view_mode = "split"
        center_layout.addWidget(self.center_splitter, 1)
        mode_row = QHBoxLayout()
        for label, mode in (("编辑", "edit"), ("分栏", "split"), ("预览", "preview")):
            button = QToolButton()
            button.setText(label)
            button.setObjectName("modeButton")
            button.clicked.connect(lambda _=False, value=mode: self.set_view_mode(value))
            mode_row.addWidget(button)
        mode_row.addSpacing(8)
        self.wrap_button = QToolButton()
        self.wrap_button.setObjectName("modeButton")
        self.wrap_button.setText("↔  自动换行")
        self.wrap_button.setPopupMode(QToolButton.InstantPopup)
        self.wrap_button.setToolTip("选择编辑栏或预览栏的自动换行设置")
        self.wrap_menu = QMenu(self)
        self.editor_wrap_action = self.wrap_menu.addAction("编辑栏启用")
        self.editor_wrap_action.setCheckable(True)
        self.preview_wrap_action = self.wrap_menu.addAction("预览栏启用")
        self.preview_wrap_action.setCheckable(True)
        self.editor_wrap_action.toggled.connect(lambda checked: self.toggle_word_wrap("editor", checked))
        self.preview_wrap_action.toggled.connect(lambda checked: self.toggle_word_wrap("preview", checked))
        self.wrap_button.setMenu(self.wrap_menu)
        editor_wrap = str(self.settings.value("editor_wrap", "false")).lower() == "true"
        preview_wrap = str(self.settings.value("preview_wrap", "false")).lower() == "true"
        self.editor_wrap_action.setChecked(editor_wrap)
        self.preview_wrap_action.setChecked(preview_wrap)
        mode_row.addWidget(self.wrap_button)
        wrap_shortcut = QAction("切换自动换行", self)
        wrap_shortcut.setShortcut(QKeySequence("Alt+Z"))
        wrap_shortcut.triggered.connect(self.toggle_word_wrap_shortcut)
        self.addAction(wrap_shortcut)
        mode_row.addStretch()
        center_layout.addLayout(mode_row)

        right = QWidget()
        self.right_panel = right
        right.setObjectName("panel")
        right_layout = QVBoxLayout(right)
        right_header = QHBoxLayout()
        right_title = QLabel("辅助面板")
        right_title.setObjectName("panelTitle")
        right_header.addWidget(right_title)
        right_header.addStretch()
        right_collapse = QToolButton()
        right_collapse.setObjectName("panelCollapseButton")
        right_collapse.setText("‹")
        right_collapse.setToolTip("收起右侧辅助面板")
        right_collapse.clicked.connect(self.toggle_right_panel)
        right_header.addWidget(right_collapse)
        right_layout.addLayout(right_header)
        self.right_tabs = QTabWidget()
        self.toc = QTreeWidget()
        self.toc.setHeaderHidden(True)
        self.toc.itemClicked.connect(self.jump_to_heading)
        self.tasks = QTreeWidget()
        self.tasks.setHeaderLabels(["任务", "状态"])
        self.tasks.itemClicked.connect(self.jump_to_task)
        self.info = QLabel("暂无项目")
        self.info.setWordWrap(True)
        self.info.setObjectName("info")
        self.right_tabs.addTab(self.toc, "文档目录")
        self.right_tabs.addTab(self.tasks, "任务面板")
        self.right_tabs.addTab(self.info, "项目信息")
        self.right_tabs.setDocumentMode(True)
        self.right_tabs.tabBar().setUsesScrollButtons(False)
        self.right_tabs.tabBar().setExpanding(True)
        self.right_tabs.currentChanged.connect(lambda *_: self.schedule_layout_save())
        right_layout.addWidget(self.right_tabs)

        self.main_splitter = QSplitter(Qt.Horizontal)
        self.main_splitter.addWidget(left)
        self.main_splitter.addWidget(center)
        self.main_splitter.addWidget(right)
        self.main_splitter.setChildrenCollapsible(False)
        self.main_splitter.setSizes([280, 860, 300])
        self.main_splitter.setStretchFactor(1, 1)
        self.main_splitter.setStretchFactor(2, 0)
        self.main_splitter.splitterMoved.connect(lambda *_: self.schedule_layout_save())
        self.center_splitter.splitterMoved.connect(lambda *_: self.schedule_layout_save())
        layout.addWidget(self.main_splitter)
        self.setStatusBar(QStatusBar())
        self.zoom_label = QLabel()
        self.zoom_label.setObjectName("zoomBadge")
        self.statusBar().addPermanentWidget(self.zoom_label)
        self.update_zoom_label()
        self.set_view_mode("split")
